In [6]:
install.packages("ggplot2")

Warning message:
"dependencies 'MASS', 'lattice' are not available"also installing the dependencies 'colorspace', 'utf8', 'nlme', 'Matrix', 'farver', 'labeling', 'munsell', 'R6', 'RColorBrewer', 'viridisLite', 'fansi', 'magrittr', 'pillar', 'pkgconfig', 'cli', 'glue', 'gtable', 'isoband', 'lifecycle', 'mgcv', 'rlang', 'scales', 'tibble', 'vctrs', 'withr'




  There are binary versions available but the source versions are later:
              binary  source needs_compilation
colorspace     2.0-1   2.1-0              TRUE
utf8           1.2.1   1.2.4              TRUE
nlme         3.1-152 3.1-164              TRUE
Matrix         1.3-3   1.6-5              TRUE
farver         2.1.0   2.1.1              TRUE
labeling       0.4.2   0.4.3             FALSE
R6             2.5.0   2.5.1             FALSE
RColorBrewer   1.1-2   1.1-3             FALSE
viridisLite    0.4.0   0.4.2             FALSE
fansi          0.4.2   1.0.6              TRUE
magrittr       2.0.1   2.0.3              TRUE
pillar         1.6.0   1.9.0             FALSE
cli            2.5.0   3.6.2              TRUE
glue           1.4.2   1.7.0              TRUE
gtable         0.3.0   0.3.4             FALSE
isoband        0.2.4   0.2.7              TRUE
lifecycle      1.0.0   1.0.4             FALSE
mgcv          1.8-35   1.9-1              TRUE
rlang         0.4.11   1.1.3     

installing the source packages 'labeling', 'R6', 'RColorBrewer', 'viridisLite', 'pillar', 'gtable', 'lifecycle', 'withr', 'ggplot2'

Warning message in install.packages("ggplot2"):
"installation of package 'lifecycle' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'pillar' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'gtable' had non-zero exit status"Warning message in install.packages("ggplot2"):
"installation of package 'ggplot2' had non-zero exit status"

In [2]:
1

[1] 1

In [3]:
1+1

[1] 2

In [4]:
a <- 1

In [5]:
b = 1

In [7]:
a == b

[1] TRUE

In [8]:
class(a)

[1] "numeric"

In [9]:
class(b)

[1] "numeric"

In [11]:
msg = "hola"
msg

[1] "hola"

In [12]:
3+2

[1] 5

In [13]:
5*3

[1] 15

In [14]:
12/2

[1] 6

In [15]:
2**3

[1] 8

In [ ]:
x = c(0.5, 0.6)        ## Numérico
x = c(TRUE, FALSE)     ## Logical
x = c(T, F)            ## Logical
x = c("a", "b", "c")   ## Caracter
x = 9:29               ## Integer
x = c(1+0i, 2+4i)      ## Complejo

In [16]:
y = c(1.7, "a")  ##Caracter
y

[1] "1.7" "a"

In [23]:
class(y)

[1] "character"

In [17]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [21]:
x = vector("numeric", (lenght = 10))
x

[1] 0 0 0 0 0 0 0 0 0 0

In [ ]:
y = c(TRUE, 2)      ##Numeric
paste

In [24]:
m = matrix(nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [25]:
dim(m)

[1] 2 3

In [26]:
m = matrix(1:6, nrow = 2, ncol = 3)
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [29]:
x = 1:3
y = 10:12
cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [30]:
rbind(x, y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [31]:
x = list(1, "a", TRUE, 1, 4i)
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1

[[5]]
[1] 0+4i

In [32]:
x = factor(c("yes", "yes", "no", "yes", "no"))
x

[1] yes yes no  yes no 
Levels: no yes

In [33]:
x = c(1, 2, NA, 10, 30)
x

[1]  1  2 NA 10 30

In [34]:
is.na(x)  ##Devuelve un vector lógico indicado que elementos son NA

[1] FALSE FALSE  TRUE FALSE FALSE

In [35]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [36]:
class(iris)

[1] "data.frame"

In [1]:
#install.packages("tidyverse")
#conda install -c r tidyverse

In [2]:
remove.packages("tidyverse")

Removing package from 'C:/Users/52332/anaconda3/Lib/R/library'
(as 'lib' is unspecified)


ERROR: Error in find.package(pkgs, lib): there is no package called 'tidyverse'


In [3]:
install.packages('tidyverse', type = 'binary')


  There is a binary version available (and will be installed) but the
  source version is later:
          binary source
tidyverse  1.3.1  2.0.0



also installing the dependencies 'markdown', 'tinytex', 'assertthat', 'lifecycle', 'tidyselect', 'gargle', 'gtable', 'MASS', 'callr', 'knitr', 'rmarkdown', 'broom', 'crayon', 'dbplyr', 'dtplyr', 'forcats', 'googledrive', 'googlesheets4', 'ggplot2', 'hms', 'modelr', 'pillar', 'reprex', 'rvest', 'stringr'



package 'markdown' successfully unpacked and MD5 sums checked
package 'tinytex' successfully unpacked and MD5 sums checked
package 'assertthat' successfully unpacked and MD5 sums checked
package 'lifecycle' successfully unpacked and MD5 sums checked
package 'tidyselect' successfully unpacked and MD5 sums checked
package 'gargle' successfully unpacked and MD5 sums checked
package 'gtable' successfully unpacked and MD5 sums checked
package 'MASS' successfully unpacked and MD5 sums checked
package 'callr' successfully unpacked and MD5 sums checked
package 'knitr' successfully unpacked and MD5 sums checked
package 'rmarkdown' successfully unpacked and MD5 sums checked
package 'broom' successfully unpacked and MD5 sums checked
package 'crayon' successfully unpacked and MD5 sums checked
package 'dbplyr' successfully unpacked and MD5 sums checked
package 'dtplyr' successfully unpacked and MD5 sums checked
package 'forcats' successfully unpacked and MD5 sums checked
package 'googledrive' succe

In [42]:
data (mpg)
mpg

Warning message in data(mpg):
"data set 'mpg' not found"

ERROR: Error in eval(expr, envir, enclos): objeto 'mpg' no encontrado
